#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-msrest
Version  : 0.6.21
Release  : 45
URL      : https://files.pythonhosted.org/packages/bb/2c/e8ac4f491efd412d097d42c9eaf79bcaad698ba17ab6572fd756eb6bd8f8/msrest-0.6.21.tar.gz
Source0  : https://files.pythonhosted.org/packages/bb/2c/e8ac4f491efd412d097d42c9eaf79bcaad698ba17ab6572fd756eb6bd8f8/msrest-0.6.21.tar.gz
Summary  : AutoRest swagger generator Python client runtime.
Group    : Development/Tools
License  : MIT
Requires: pypi-msrest-python = %{version}-%{release}
Requires: pypi-msrest-python3 = %{version}-%{release}
Requires: requests-oauthlib
BuildRequires : buildreq-distutils3
Provides: msrest
Provides: msrest-python
Provides: msrest-python3
BuildRequires : pypi(certifi)
BuildRequires : pypi(isodate)
BuildRequires : pypi(requests)
BuildRequires : pypi(requests_oauthlib)
BuildRequires : requests-oauthlib

%description
===============================

%package python
Summary: python components for the pypi-msrest package.
Group: Default
Requires: pypi-msrest-python3 = %{version}-%{release}

%description python
python components for the pypi-msrest package.


%package python3
Summary: python3 components for the pypi-msrest package.
Group: Default
Requires: python3-core
Provides: pypi(msrest)
Requires: pypi(certifi)
Requires: pypi(isodate)
Requires: pypi(requests)
Requires: pypi(requests_oauthlib)

%description python3
python3 components for the pypi-msrest package.


%prep
%setup -q -n msrest-0.6.21
cd %{_builddir}/msrest-0.6.21

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641456613
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
